[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501
address = "0.0.0.0"
maxUploadSize = 50

[browser]
serverAddress = "os.holisticjson.pl"
serverPort = 443
gatherUsageStats = false
