# Dockerfile for Fala Życia Static Nginx Web Portal (fala-zycia-web)
FROM nginx:alpine

ENV NGINX_ENVSUBST_FILTER="PORT"

COPY nginx.conf /etc/nginx/templates/default.conf.template

COPY . /usr/share/nginx/html/

EXPOSE 8080
