FROM nginx:alpine

ENV NGINX_ENVSUBST_FILTER="PORT"

# Support both root context and 02-website context
COPY 02-website/nginx.conf /etc/nginx/templates/default.conf.template

COPY 02-website /usr/share/nginx/html/

EXPOSE 8080
