server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Zapewnienie obsługi ewentualnych ścieżek bez rozszerzenia
    location ~ ^/([^/]+)$ {
        try_files $uri $uri/ /$1.html =404;
    }
}
